### ISSUE TITLE
ERROR  Nuxt Build Error: [vite:vue] failed to resolve "extends":"./.nuxt/tsconfig.json" in lyx-ui/tsconfig.json

### ISSUE THREAD

**Issue by yonas** [Litlyx/litlyx#13]
```sh
$ yarn build
yarn run v1.22.19
$ nuxt build
Nuxt 3.12.4 with Nitro 2.9.7                                                                                                                                                                            11:31:54 AM
Using 2024-04-03 as fallback compatibility date.                                                                                                                                                        11:31:56 AM
ℹ Nuxt Icon server bundle mode is set to local                                                                                                                                                         11:31:56 AM
ℹ Using default Tailwind CSS file                                                                                                                                                     nuxt:tailwindcss 11:31:57 AM
ℹ Building client...                                                                                                                                                                                   11:32:03 AM
ℹ vite v5.4.1 building for production...                                                                                                                                                               11:32:03 AM

[11:32:22 AM]  WARN  [plugin:vite:resolve] [plugin vite:resolve] Module "https" has been externalized for browser compatibility, imported by "/tmp/f/dashboard/node_modules/litlyx-js/node/requester.js". See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.


[11:32:22 AM]  WARN  [plugin:vite:resolve] [plugin vite:resolve] Module "http" has been externalized for browser compatibility, imported by "/tmp/f/dashboard/node_modules/litlyx-js/node/requester.js". See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.

ℹ ✓ 307 modules transformed.                                                                                                                                                                           11:32:23 AM

 ERROR  x Build failed in 20.34s                                                                                                                                                                        11:32:23 AM


 ERROR  Nuxt Build Error: [vite:vue] failed to resolve "extends":"./.nuxt/tsconfig.json" in /tmp/f/lyx-ui/tsconfig.json                                                                                 11:32:23 AM
file: /tmp/f/lyx-ui/components/Button.vue

  file: /tmp/f/lyx-ui/components/Button.vue
  at resolveExtends (node_modules/vite/dist/node/chunks/dep-Cy9twKMn.js:18815:8)
  at parseExtends (node_modules/vite/dist/node/chunks/dep-Cy9twKMn.js:18750:24)
  at parse$e (node_modules/vite/dist/node/chunks/dep-Cy9twKMn.js:18608:23)
  at async loadTsconfigJsonForFile (node_modules/vite/dist/node/chunks/dep-Cy9twKMn.js:19403:20)
  at async transformWithEsbuild (node_modules/vite/dist/node/chunks/dep-Cy9twKMn.js:19164:30)
  at async transformMain (node_modules/@vitejs/plugin-vue/dist/index.mjs:2533:34)
  at async transform (node_modules/rollup/dist/es/shared/node-entry.js:18787:16)
  at async ModuleLoader.addModuleSource (node_modules/rollup/dist/es/shared/node-entry.js:19003:36)
```

commit: 1b88bad

**Comment by AntonioVerdiglione1996** [comment]
Try the new version!
